### PR TITLE
gender TextView to spinner

### PR DESCRIPTION
**Pull request by HorilPrasad**
Update the UI for gender selection from TextView to Spinner

### CODE REVIEW

**Comment by iamanantshukla** [comment]
The drop down arrow is not aligning with the other fields in the activity.
InkedScreenshot_20221003-113307
Should be similar to select your blood group.

**Comment by HorilPrasad** [comment]
Screenshot_20221003_120724

**Comment by iamanantshukla** [comment]
Add .idea folder to .gitignore.

**Comment by HorilPrasad** [comment]
Plz merge this PR.

**Comment by HorilPrasad** [comment]
Why have I not gotten any points till now? After merging the PR.

**Comment by iamanantshukla** [comment]
You must have got it now, if not please let me know.

**Pull request merged**
