### PR TITLE
Issue #8 Fetch government blood bank data solved

### PR DESCRIPTION
**Pull request by Gagan1729-droid**

### CODE REVIEW

**Comment by iamanantshukla** [comment]
Comparator function for sorting the blood banks is throwing "Comparison method violates its general contract".

**Comment by Gagan1729-droid** [comment]
Rectified the comparator issue. Please check it.

**Comment by iamanantshukla** [comment]
Testing it on API 27 and getting follow error: https://wtools.io/paste-code/bGlk
Try this: https://stackoverflow.com/a/11620614

**Comment by Gagan1729-droid** [comment]
Should be working fine now..

**Pull request merged**
